name: Sync Image to My DockerHub

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull and Push
        run: |
          docker pull platane/snk:3.3.0
          docker tag platane/snk:3.3.0 robinsonsajid/snake:1.0.0
          docker push robinsonsajid/snake:1.0.0
